{% set name = "gcsfs" %}
{% set version = "2023.12.2" %}
{% set sha256 = "8ada5d194c425f687f71a202294c65ca255b2905313da2e713c62c0e6adc2607" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - google-auth >=1.2
    - google-auth-oauthlib
    - google-cloud-storage >1.40
    - requests
    - decorator >4.1.2
    - fsspec =={{ version }}
    - aiohttp

test:
  imports:
    - gcsfs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: http://gcsfs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
