{% set name = "gcsfs" %}
{% set version = "2025.3.1" %}
{% set sha256 = "84b9899ff9a33a4238b6400e5edebc8a87cf81d7c45c300e318e08c1214e2f5e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - google-auth >=1.2
    - google-auth-oauthlib
    - google-cloud-storage >1.40
    - requests
    - decorator >4.1.2
    - fsspec =={{ version }}
    - aiohttp

test:
  imports:
    - gcsfs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: http://gcsfs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
